### PR TITLE
CldOgImage Types Missing Definitions

### LINKED ISSUE #166: Can't Pass Overlays to `CldOGImage`
# **Bug Report**

## **Describe the bug**

When I try to pass `overlays` as a property to `CldOGImage`, I get a TypeScript error.

image

## **Steps To Reproduce the error**

Pass an overlays object to the `CldOGImage` component

## **Expected behaviour**

I expect to be able to pass the same props to the OG component as the regular `CldImage` component.

### PR DESCRIPTION
**Pull request by colbyfayock**
# Description

Currently some options are missing on CldOgImage Types including `overlays` which cause an error if attempted to be used in TypeScript.

This borrows the CldImage props, as it's basically the same, and uses ImageOptions from the URL construction to ensure everything checks out and is available.

## Issue Ticket Number

Fixes #166 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Fix or improve the documentation
- [ ] This change requires a documentation update

# Checklist

- [ ] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [ ] I have created an [issue](https://github.com/colbyfayock/next-cloudinary/issues) ticket for this PR
- [ ] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/next-cloudinary/pulls) for the same update/change?
- [ ] I have performed a self-review of my own code
- [ ] I have run tests locally to ensure they all pass
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx [hunk 1]
```diff
@@ -1,29 +1,26 @@
...
-  gravity?: string;
-  height: string | number;
-  src: string;
   twitterTitle?: string;
-  width: string | number;
 }
 
 const CldOgImage = ({ excludeTags = [], twitterTitle, ...props }: CldOgImageProps) => {
-  const options = {
+  const { alt } = props;
```
Comment (jamesqquick) [inline next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:20]: Why not destructure this in the function parameter definition along with the other parameters?

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx [hunk 2]
```diff
@@ -1,29 +1,26 @@
...
+
+  const options: ImageOptions = {
     ...props,
-    alt: props.alt,
     crop: props.crop || 'fill',
     gravity: props.gravity || 'center',
     height: props.height || IMAGE_HEIGHT,
```
Comment (jamesqquick) [inline next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:26]: height and width should probably not be removed from the incoming params definition since they are being referenced here? That way, user can override?

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx [hunk 3]
```diff
@@ -56,8 +53,8 @@ const CldOgImage = ({ excludeTags = [], twitterTitle, ...props }: CldOgImageProp
       <meta property="og:image:width" content={`${options.width}`} />
       <meta property="og:image:height" content={`${options.height}`} />
 
-      {options.alt && (
-        <meta property="og:image:alt" content={options.alt} />
+      {alt && (
+        <meta property="og:image:alt" content={alt} />
```
Comment (jamesqquick) [inline next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:57]: Any reason to destructure alt specifically above insetad of referencing it from `options.alt` as you did originally?

**Review by jamesqquick — CHANGES_REQUESTED** [review]

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx (hunk 1 above)
Comment (colbyfayock) [reply next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:20]: the other `options` get passed into `constructCloudinaryUrl` which doesnt take an `alt` parameter, so they're never actually used together

its only used alone in its own meta tag

Comment (jamesqquick) [reply next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:20]: Understood!

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx (hunk 2 above)
Comment (colbyfayock) [reply next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:26]: yeah you're right. i think i got mixed up because it has default, but it still needs types

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx (hunk 3 above)
Comment (colbyfayock) [reply next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:57]: it was just part of the cleanup to remove it from alt

i dont know that removing it from options matters (per my other comment) but it felt more correct since the options were intended to be for the constructCloudinaryUrl function

Comment (jamesqquick) [reply next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:57]: 👍

**Review by jamesqquick — APPROVED** [review]

**Comment by colbyfayock** [comment]
thanks for help with the review @jamesqquick
