### PR TITLE
Make `tsc` directly emit typescript declarations

### LINKED ISSUE #106: [Bug] Outputted type definitions are referencing the wrong path
# **Bug Report**

## **Describe the bug**

`dist/index.d.ts` is attempting to import the directory instead of the individual file, which is causing projects using the package to not correctly be able to utilize the types.

```js
export { default as CldImage } from './components/CldImage';
export { default as CldOgImage } from './components/CldOgImage';
```

I think this should be:

```js
export { default as CldImage } from './components/CldImage/CldImage';
export { default as CldOgImage } from './components/CldOgImage/CldOgImage';
```

## **Is this a regression?**

New bug based on my work to add typescript.

## **Expected behaviour**

When used as a dependency, projects should correctly see types for all the components.

### **Your environment**

N/A

## **Additional context**

I'll go ahead and work on this, should be pretty simple to fix.

### PR DESCRIPTION
**Pull request by tanzoniteblack**
# Description

microbundler/rollup were doing it wrong, by not emitting the `index.d.ts` files per component, but tsc directly creates the declarations correctly. The `tsconfig.json` now specifies that declarations need to be emitted by the typescript compiler and sticks them into the appropriate build folder.

## Issue Ticket Number

Fixes #106 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Fix or improve the documentation
- [ ] This change requires a documentation update

# Checklist

- [x] I have followed the contributing guidelines of this project as mentioned in [CONTRIBUTING.md](/CONTRIBUTING.md)
- [x] I have created an [issue](https://github.com/colbyfayock/next-cloudinary/issues) ticket for this PR
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/colbyfayock/next-cloudinary/pulls) for the same update/change?
- [x] I have performed a self-review of my own code
- [x] I have run tests locally to ensure they all pass
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes needed to the documentation

### CODE REVIEW

File: next-cloudinary/src/components/CldOgImage/CldOgImage.tsx [hunk 1]
```diff
@@ -24,7 +24,8 @@ const CldOgImage = ({ excludeTags = [] as string[], twitterTitle, ...props }) =>
   // We need to include the tags within the Next.js Head component rather than
   // direcly adding them inside of the Head otherwise we get unexpected results
 
-  return (
+    return (
+    // @ts-ignore
```
Comment (tanzoniteblack) [inline next-cloudinary/src/components/CldOgImage/CldOgImage.tsx:28]:
```
TS2741: Property 'children' is missing in type '{}' but required in type '{ children: React.ReactNode; }'.
```

Didn't fix this in this PR because I'm not really sure _how_ it should be addressed, and didn't want to bloat the PR by doing so

**Comment by tanzoniteblack** [comment]
when I updated the typescript config to rely more directly on tsc than microbundler, I had to add a few `@ts-ignore` lines due to new errors that were found. These need addressed, but currently nothing in this PR effects any existing code that's used as a library.

File: next-cloudinary/src/components/CldUploadButton/CldUploadButton.tsx [hunk 2]
```diff
@@ -9,8 +9,9 @@ const CldUploadButton = ({
   uploadPreset,
   ...props
 }) => {
-  return (
+    return (
     <>
+      {/*  @ts-ignore */}
```
Comment (tanzoniteblack) [inline next-cloudinary/src/components/CldUploadButton/CldUploadButton.tsx:14]:
```
TS2741: Property 'children' is missing in type '{ onUpload: any; options: any; signatureEndpoint: any; uploadPreset: any; }' but required in type '{ children: any; onUpload: any; options: any; signatureEndpoint: any; uploadPreset: any; }'.
```

File: next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx [hunk 3]
```diff
@@ -107,6 +106,7 @@ const CldUploadWidget = ({
       })}
       <Script
         id={`cloudinary-${Math.floor(Math.random() * 100)}`}
+        // @ts-ignore
```
Comment (tanzoniteblack) [inline next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx:109]:
```
TS2322: Type '{ id: string; src: string; onLoad: () => void; onError: (e: any) => void; }' is not assignable to type 'ScriptProps'.   Property 'src' does not exist on type 'ScriptProps'.
```

**Comment by colbyfayock** [comment]
hey @tanzoniteblack looks like Vercel is failing in build when trying to build the docs site, which uses it. are you able to reproduce that locally? can try running build in the next-cloudinary directory, then running build in the docs directory

**Comment by tanzoniteblack** [comment]
Whoops. That was my bad, accidentally checked in a line that wasn't allowing the full typescript transpile output to be emitted.

**Comment by colbyfayock** [comment]
awesome thanks
